title: Renan Araujo
description: Personal website and blog
url: "https://araujore.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: "2..3"
permalink: /blog/:title/
navigation:
  - title: About
    url: /
  - title: Publications
    url: /publications
  - title: Blog
    url: /blog
    hidden: true
  - title: Contact
    url: /contact
social:
  linkedin: https://www.linkedin.com/in/araujonrenan/
  twitter: https://twitter.com/araujonrenan
